packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  react: 19.1.0
  react-dom: 19.1.0
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@verdant-web/cli': 4.8.2
  '@verdant-web/common': 2.9.1
  '@verdant-web/react': 42.1.0
  '@verdant-web/store': 4.5.0
