packages:
  - 'packages/*'
  - 'docs'
  - 'test'
  - 'examples/**'
  - 'scaleTest'
  - 'scratchpad'
  - 'configs'

catalog:
  better-sqlite3: ^11.8.1
  typescript: 5.7.3
  '@types/node': 22.13.4
  vitest: 3.0.6
  '@vitest/browser': 3.0.6
  vitest-browser-react: 0.1.1
  playwright: 1.50.1
  react: 19.0.0
  '@types/react': 19.0.10
  vite: 6.1.1
  '@vitejs/plugin-react': 4.3.4
  react-dom: 19.0.0
  '@types/react-dom': 19.0.4
